import boundary from "./boundary";
import mount from "./mount";
import passProps from "./passProps";
import elementRef from "./elementRef";
import rerender from "./rerender";
import hydrate from "./hydrate";
import unmount from "./unmount";
import nodeState from "./nodeState";
import replaceByKey from "./replaceByKey";
import skipRender from "./skipRender";
import clearsProps from "./clearsProps";
import shouldUpdate from "./shouldUpdate";

boundary();
mount();
passProps();
elementRef();
rerender();
hydrate();
unmount();
nodeState();
replaceByKey();
skipRender();
clearsProps();
shouldUpdate();
