import mount from "./mount";
import boundary from "./boundary";
import passProps from "./passProps";
import elementRef from "./elementRef";
import rerender from "./rerender";
import hydrate from "./hydrate";
import componentUnmount from "./componentUnmount";
import componentMount from "./componentMount";
import nodeState from "./nodeState";
import replaceByKey from "./replaceByKey";
import clearsOldProps from "./clearsOldProps";
import shouldUpdate from "./shouldUpdate";
import renderPrimitives from "./renderPrimitives";
import assertIsComponent from "./assertIsComponent";
import rendersArraysInChildren from "./rendersArraysInChildren";
import rerenderChild from "./rerenderChild";
import afterRender from "./afterRender";
import componentFragment from "./componentFragment";
import fragmentMountRunsOnce from "./fragmentMountRunsOnce";
import fragmentUnmountRunsOnce from "./fragmentUnmountRunsOnce";
import replacingFragmentWithNodeWontUnmount from "./replacingFragmentWithNodeWontUnmount";
import childWithFragmentUnmounts from "./childWithFragmentUnmounts";
import rerenderMayUnmountParents from "./rerenderMayUnmountParents";
import rerenderMayChangeRootNode from "./rerenderMayChangeRootNode";
import dangerouslySetInnerHTML from "./dangerouslySetInnerHTML";

mount();
boundary();
passProps();
elementRef();
rerender();
hydrate();
componentUnmount();
componentMount();
nodeState();
replaceByKey();
clearsOldProps();
shouldUpdate();
renderPrimitives();
assertIsComponent();
rendersArraysInChildren();
rerenderChild();
afterRender();
componentFragment();
fragmentMountRunsOnce();
fragmentUnmountRunsOnce();
replacingFragmentWithNodeWontUnmount();
childWithFragmentUnmounts();
rerenderMayUnmountParents();
rerenderMayChangeRootNode();
dangerouslySetInnerHTML();
